from . import ControlModule

class _HomeStatusModule(ControlModule):
    def __init__(self):
        self.module_config = {
            "module_name":"homestatus",
            "display_name":"Home Status",
            "polling_period_seconds":-1
            }

    def get_data(self):

        # Return data
        data = dict()

        # Return the retrieved data along with an interpretation function
        return (data, _HomeStatusModule._interpret_data)

    @staticmethod
    def _interpret_data(data):
        """ Interpret the given data as generated by the associated class 
        "get_data" and return data of note (i.e. non-nominal values)
        """

        alert_items = []

        return alert_items

instance = _HomeStatusModule()
