from . import ControlModule

class _WeatherModule(ControlModule):
    def __init__(self):
        self.module_config = {
            "module_name":"weather",
            "display_name":"Weather",
            "polling_period_seconds":-1
            }

    def get_data(self):

        # Return data
        data = dict()

        # Return the retrieved data along with an interpretation function
        return ControlModule.ReturnItem(data, _WeatherModule._interpret_data)

    @staticmethod
    def _interpret_data(data, dash):
        """ Interpret the given data as generated by the associated class 
        "get_data" and return data of note (i.e. non-nominal values). Update
        the given dashboard.
        """

        alert_items = []
        report_items = dict()

        dash.update_weather(report_items)

        return alert_items

instance = _WeatherModule()
